services:
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_PORT=${SEARXNG_PORT:-8080}
      - SEARXNG_BIND_ADDRESS=${SEARXNG_BIND_ADDRESS:-0.0.0.0}
      - SEARXNG_URL=${SEARXNG_URL:-/}
    restart: always
    networks:
      default:

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      ## Ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}

      ## Searxng
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUEST=10
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>

      ## Web
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=${OAUTH_MERGE_ACCOUNTS_BY_EMAIL:-false}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-secret}
      - USE_CUDA_DOCKER=${USE_CUDA_DOCKER:-false}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:P@55w0rd@postgres:5432/postgres}

    restart: always
    volumes:
      - open_webui:/app/backend/data
    networks:
      default:

  postgres:
    image: postgres:${PG_MAJOR:-latest}
    environment:
      - TZ=${TIMEZONE:-Australia/Brisbane}
      - POSTGRES_DB=${POSTGRES_DB:-postgress}
      - POSTGRES_USER=${POSTGRES_USER:-postgress}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-P@55w0rd}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-P@55w0rd}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      default:

volumes: 
  open_webui:
  postgres:
