services:
#  ollama:
    # NVIDIA GPU
    # image: ollama/ollama:latest
    #### uncomment the following line to use the GPU
    # deploy:
    #   replicas: 1
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    # AMD GPU
    # image: ollama/ollama:rocm
    # devices:
    #   - /dev/kfd:/dev/kfd
    #   - /dev/dri:/dev/dri
    # volumes:
    #   - /opt/amdgpu:/opt/amdgpu:ro
    #   - /home/ollama/.ollama:/root/.ollama
    # environment:
    #   - OLLAMA_MAX_LOADED_MODELS=${OLLAMA_MAX_LOADED_MODELS:-1}
    #   - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-}

#    healthcheck:
#      test: timeout 5 bash -c "</dev/tcp/localhost/11434"
#      interval: 10s
#      timeout: 30s
#      retries: 5
#      start_period: 15s
#    restart: always
#    networks:
#      default:

  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET:-secret}
      - SEARXNG_BIND_ADDRESS=${SEARXNG_BIND_ADDRESS:-0.0.0.0}
      - SEARXNG_PORT=${SEARXNG_PORT:-8080}
      - SEARXNG_URL=${SEARXNG_URL:-/}
    restart: always
    networks:
      default:

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    ports:
      - "8080:8080"
    depends_on:
#      ollama:
#        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      ## Ollama
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}

      ## Searxng
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUEST=10
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>

      ## Web
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=${OAUTH_MERGE_ACCOUNTS_BY_EMAIL:-false}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-secret}
      - USE_CUDA_DOCKER=${USE_CUDA_DOCKER:-false}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:P@55w0rd@postgres:5432/postgres}

    restart: always
    volumes:
      - open_webui:/app/backend/data
    networks:
      default:

  postgres:
    image: postgres:${PG_MAJOR:-latest}
    environment:
      - TZ=${TIMEZONE:-Australia/Brisbane}
      - POSTGRES_DB=${POSTGRES_DB:-postgress}
      - POSTGRES_USER=${POSTGRES_USER:-postgress}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-P@55w0rd}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-P@55w0rd}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      default:

networks:
  default:

volumes: 
  open_webui:
  postgres:
